### ISSUE TITLE
cara settting

### ISSUE THREAD

**Issue by lordmen99** [ziahaqi/sample-uikit#2]
public static final String MERCHANT_BASE_CHECKOUT_URL = "merchant_base_checkout_url";
    public static final String MERCHANT_CLIENT_KEY = "merchant_client_key";

pada bagian ini =

MERCHANT_BASE_CHECKOUT_URL  diisi url apa y pak?

**Comment by ziahaqi** [comment]
diisi derngan url payment merchant server bapak. misalnya bapak implement url chargingnya sebagai berikut
`https://merchant.com/midtrans/payment/charge`. maka yg digunakan pada  adalah url sebelum endpoint `/charge`. sehingga menjadi `MERCHANT_BASE_CHECKOUT_URL` = `https://merchant.com/midtrans/payment`. 
sedangkan `MERCHANT_CLIENT_KEY` adalah client_key bapak yg ada di MAP midtrans.

**Comment by lordmen99** [comment]
terus untuk cek / nangkep notifikasi transaksi via mobile sdk langsung gmna yah?

**Comment by ziahaqi** [comment]
anda perlu implement listener (sdk callback)
```SdkUIFlowBuilder.init()
        .setClientKey(CLIENT_KEY) // client_key is mandatory
        .setContext(CONTEXT) // context is mandatory
        .setTransactionFinishedCallback(new TransactionFinishedCallback() {
                    @Override
                   public void onTransactionFinished(TransactionResult result) {
                       // Handle finished transaction here.
                   }
                }) // set transaction finish callback (sdk callback)
        .setMerchantBaseUrl(BASE_URL) //set merchant url (required)
        .enableLog(true) // enable sdk log (optional)
        .setColorTheme(new CustomColorTheme("#FFE51255", "#B61548", "#FFE51255")) // set theme. it will replace theme on snap theme on MAP ( optional)
        .buildSDK();```

**Comment by ziahaqi** [comment]
bisa liat disini https://mobile-docs.midtrans.com/#installation
