### ISSUE TITLE
com.midtrans.sdk.uikit.activities.UserDetailsActivity already has an action bar supplied by the window decor

### ISSUE THREAD

**Issue by ntaloventi** [ziahaqi/sample-uikit#3]
hello, im using app theme and also trial with no action bar but seems always get force close with illegal state exception: "This Activity already has an action bar supplied by the window decor"

thank you

**Comment by ziahaqi** [comment]
that's related to theme of your app. you need to implement `no action bar` as the parent of your theme. for example `<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">`
